name: npmam-docker

services:
    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - default
    php:
        container_name: php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        user: www-data
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
        tty: true
        stdin_open: true
        networks:
            - default
    mariadb:
        container_name: mariadb
        image: mariadb:lts
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./docker/mariadb:/docker-entrypoint-initdb.d:ro
        networks:
            - default
    adminer:
        container_name: adminer
        image: adminer:latest
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
            ADMINER_DESIGN: "nette"
        ports:
            - "81:8080"
        networks:
            - default
    mailer:
        container_name: mailer
        image: axllent/mailpit:latest
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - default

volumes:
    mariadb_data:
        name: db_data
        driver: local

networks:
    default:
        name: npmam-network
        driver: bridge
